{
	"susiCommData": {
		"devID": "0000000E4CABCD77",
		"parentID": "",
		"hostname": "IoTGW(CD77)",
		"sn": "000E4CABCD77",
		"mac": "000E4CABCD77",
		"version": "3.1.23",
		"type": "IoTGW",
		"product": "",
		"manufacture": "",
		"account": "",
		"passwd": "",
		"status": 1,
		"commCmd": 1,
		"requestID": 21,
		"agentID": "0000000E4CABCD77",
		"handlerName": "general",
		"sendTS": 1476067275606
	}
}
